### PR TITLE
added goveralls workaround

### PR DESCRIPTION
**Pull request by mrd0ll4r**
The issue seems to be [known](https://github.com/mattn/goveralls/issues/68) and this seems to be the way to fix it

### CODE REVIEW

**Comment by jzelinskie** [comment]
Doesn't look like it worked. Can you try force pushing to see if it was just an ephemeral issue or if this is still broken?

**Comment by mrd0ll4r** [comment]
nope, doesn't look like it works

**Comment by mrd0ll4r** [comment]
Ah, I think travis is hiding the coveralls token, as described in the [travis docs about environment variables and pull requests](https://docs.travis-ci.com/user/environment-variables)

**Comment by jzelinskie** [comment]
Closing in favor of #144. Thanks for the PR, but it looks like the tools for integrating with coveralls are just too much of a hack. See https://github.com/mattn/goveralls/pull/64 and https://github.com/mattn/goveralls/issues/68#issuecomment-198573259

**Pull request closed without merging**
