### PR TITLE
middleware: add varinterval

### PR DESCRIPTION
**Pull request by mrd0ll4r**

### CODE REVIEW

**Comment by jzelinskie** [comment]
The code looks great. How do you feel about maybe consolidating all the docs together in one place? Maybe in the `/docs` directory since github supports turning that into a static github pages website.

**Comment by mrd0ll4r** [comment]
Sure, that sounds good. That's gonna require a few additional directories and markdown files though, I'll open a PR for that stuff first, then change this one.

**Comment by jzelinskie** [comment]
umm...so I accidentally pressed the "Update branch" button on GitHub and it merged master into your branch. Can you get rid of that commit and rebase?

**Comment by mrd0ll4r** [comment]
No problem. I still have to pull out the docs - will do that tomorrow.

**Comment by mrd0ll4r** [comment]
Alright, rebased, now uses `pkg/prand`, added config example, ptal :)

**Pull request merged**
