### PR TITLE
Fix 437

### LINKED ISSUE #437: Race condition when accessing UDP server socket
`Frontend.socket` field in `udp` package is accessed from 2 goroutines. Found it with race detector while testing my program.

```
WARNING: DATA RACE
Read at 0x00c00019c100 by goroutine 32:
  .../vendor/github.com/chihaya/chihaya/frontend/udp.(*Frontend).Stop.func1()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:107 +0x93

Previous write at 0x00c00019c100 by goroutine 20:
  .../vendor/github.com/chihaya/chihaya/frontend/udp.(*Frontend).listenAndServe()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:123 +0xff
  .../vendor/github.com/chihaya/chihaya/frontend/udp.NewFrontend.func2()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:88 +0x3c
```

Set in here: https://github.com/chihaya/chihaya/blob/8f0fc7ba1086d2480f101332101e57b7137c197e/frontend/udp/frontend.go#L123

And read in here: https://github.com/chihaya/chihaya/blob/8f0fc7ba1086d2480f101332101e57b7137c197e/frontend/udp/frontend.go#L107

### PR DESCRIPTION
**Pull request by cenkalti**
Fix #437

### CODE REVIEW

**Comment by cenkalti** [comment]
@pushrax @mrd0ll4r I can do that too. Would you like me to update the PR?

**Comment by mrd0ll4r** [comment]
Yes please :) Thank you!

**Comment by jzelinskie** [comment]
Do we need to add -race flags to TravisCI to make that test effective? If so, I'd like to see that in this PR before merging.

**Comment by cenkalti** [comment]
@jzelinskie No, the tests are still failing without `-race` flag. I can open another PR for `-race` flag after this is merged.

**Pull request merged**
