### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by dvrkps** [comment]
@mrd0ll4r yap 1.x is also option. would you like that i change 1.9.x to 1.x or leave this as is ?

**Comment by mrd0ll4r** [comment]
Fine with me either way - @jzelinskie opinion?

**Comment by jzelinskie** [comment]
`go1.8` for example is also short for `go1.8.x`.
If we just remove this whole block and leave `language: go` it should do the same.

**Comment by dvrkps** [comment]
@jzelinskie @mrd0ll4r done.

**Comment by mrd0ll4r** [comment]
@jzelinskie have you tried that somewhere before? The minimal example on travis says
```
  language: go
  go:
    - 1.6
```

Even though travis builds the PR, it uses the `travis.yml` from the repository, not the PR, so I wouldn't really trust that.

**Comment by dvrkps** [comment]
@jzelinskie @mrd0ll4r without go key travis use go 1.9 instead 1.9.2 [build without go key](https://travis-ci.org/chihaya/chihaya/jobs/321141354)
may i add 1.9.x ?

**Comment by mrd0ll4r** [comment]
Oh my bad, it does use the updated `travis.yml` then. @dvrkps yes, make it `1.9.x` please. Sorry for the confusion.

**Comment by dvrkps** [comment]
@mrd0ll4r done.

**Pull request merged**
