### PR TITLE
prand: add Container

### PR DESCRIPTION
**Pull request by mrd0ll4r**
I need this for the deniability and varinterval middleware to be able to handle multiple requests in parallel.

### CODE REVIEW

**Comment by jzelinskie** [comment]
Can we put this in a `pkg/prand` and add a package description that this allows parallel access to randomness.

**Comment by mrd0ll4r** [comment]
ptal

**Comment by jzelinskie** [comment]
I'm a fan of hiding locks from APIs. I'd rather have the locking behavior internal to the type so that the caller can't shoot themselves in the foot. Also coupling the locks with the thing they lock into the same object is another thing I usually do. So in this example `Container` could be a `[]struct{rand, mutex}` (pseudo-code).

**Comment by mrd0ll4r** [comment]
Putting the locks with the rands into a struct should generate a more local layout in memory, makes sense, will do.

But I can't hide the locking from the user. Sure, I could call the methods `Get(n int)` or `GetByInfohash(ih)`, but the user still has to call some method to get a `*rand.Rand` and some method to return it.

**Comment by mrd0ll4r** [comment]
I updated this btw, ptal :)

**Comment by jzelinskie** [comment]
Let me just confirm I understand this PR:

You need randomness for the aforementioned two middleware. `math/rand`'s exported functions are already locked, but to enable performance you want multiple sources of randomness so that everything isn't contending for the same lock.

Can you post an example of where you'd use this package? Without seeing more, I can't understand why you wouldn't want to implement roughly the same API as [`math/rand.Rand`](https://godoc.org/math/rand#Rand).

**Comment by mrd0ll4r** [comment]
> You need randomness for the aforementioned two middleware. math/rand's exported functions are already locked, but to enable performance you want multiple sources of randomness so that everything isn't contending for the same lock.

Yup, that's exactly it. If we have one of these middleware in the chain and they effectively run single-threaded our whole chain is stalled.

For example: The deniability middleware uses it [like this](https://github.com/mrd0ll4r/chihaya/blob/71edd693308c83836d767f533da297f218994d6e/middleware/deniability/deniability.go#L149). I implemented this PR manually a few lines earlier. I need basically the same functionality for the varinterval middleware, but don't want to copy the implementation.

Now for why this API: Implementing `math/rand.Rand` is huge and needs to behave (i.e. produce the same kind of numbers as) the stdlib. I thought about implementing a `rand.Source` that works in parallel, but in order to use that in parallel you'd need multiple `rand.Rand`s feeding off that, which brings us back to the multiple-`rand.Rand`s approach I took here.

A lot of benchmarking went into this: I tried channel-based solutions, lock-free slices of channels, and also pooling the actual values (let's say a `chan float64` that is written to by multiple goroutines calling `Float64()` on a local `rand.Rand`), but all of them perform poorly. The only thing that is as fast as (and occasionally faster than) this solution is a `sync.Pool`. That would be the only viable alternative, but I dislike it because noone really knows what it does and it introduces some nondeterminism. (Also the performance is very close, on my laptop the difference is ~4 ns.)

So yeah, implementing just the API I need (some `float64`s, `int`s, and `byte`s, iirc) would work, but is too slow and too specific to be a `pkg/prand`. All middleware that needs randomness needs to be able to handle multiple requests in parallel - I don't want to force future middleware to use a small subset of API `rand.Rand` provides.

**Comment by jzelinskie** [comment]
This sounds fair to me. I'm willing to LGTM after a rebase.

**Comment by mrd0ll4r** [comment]
Rebased, small optimization, ptal

**Pull request merged**
